export const LOADING_PROJECT = 'LOADING_PROJECT';
export const LOADING_PROJECT_SUCCESS = 'LOADING_PROJECT_SUCCESS';
export const LOADING_PROJECT_FAILURE = 'LOADING_PROJECT_FAILURE';

export const LOADING_POSTS = 'LOADING_POSTS';
export const LOADING_POSTS_SUCCESS = 'LOADING_POSTS_SUCCESS';
export const LOADING_POSTS_FAILURE = 'LOADING_POSTS_FAILURE';
export const LOADING_POSTS_MORE = 'LOADING_POSTS_MORE';
export const LOADING_POSTS_MORE_SUCCESS = 'LOADING_POSTS_MORE_SUCCESS';
export const LOADING_POSTS_MORE_FAILURE = 'LOADING_POSTS_MORE_FAILURE';

export const LOADING_ARTICLE = 'LOADING_ARTICLE';
export const LOADING_ARTICLE_SUCCESS = 'LOADING_ARTICLE_SUCCESS';
export const LOADING_ARTICLE_FAILURE = 'LOADING_ARTICLE_FAILURE';

export const LOADING_ARCHIVES = 'LOADING_ARCHIVES';
export const LOADING_ARCHIVES_SUCCESS = 'LOADING_ARCHIVES_SUCCESS';
export const LOADING_ARCHIVES_FAILURE = 'LOADING_ARCHIVES_FAILURE';

export const LOADING_COMMENT = 'LOADING_COMMENT';
export const LOADING_COMMENT_SUCCESS = 'LOADING_COMMENT_SUCCESS';
export const LOADING_COMMENT_FAILURE = 'LOADING_COMMENT_FAILURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const LOADING_ABOUT = 'LOADING_ABOUT';
export const LOADING_ABOUT_SUCCESS = 'LOADING_ABOUT_SUCCESS';
export const LOADING_ABOUT_FAILURE = 'LOADING_ABOUT_FAILURE';

export const LOADING_MESSAGE = 'LOADING_MESSAGE';
export const LOADING_MESSAGE_SUCCESS = 'LOADING_MESSAGE_SUCCESS';
export const LOADING_MESSAGE_FAILURE = 'LOADING_MESSAGE_FAILURE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';