export const LOADING_PROJECT = 'LOADING_PROJECT';
export const LOADING_PROJECT_SUCCESS = 'LOADING_PROJECT_SUCCESS';
export const LOADING_PROJECT_FAILURE = 'LOADING_PROJECT_FAILURE';

export const LOADING_POSTS = 'LOADING_POSTS';
export const LOADING_POSTS_SUCCESS = 'LOADING_POSTS_SUCCESS';
export const LOADING_POSTS_FAILURE = 'LOADING_POSTS_FAILURE';

export const LOADING_ARTICLE = 'LOADING_ARTICLE';
export const LOADING_ARTICLE_SUCCESS = 'LOADING_ARTICLE_SUCCESS';
export const LOADING_ARTICLE_FAILURE = 'LOADING_ARTICLE_FAILURE';

export const LOADING_ARCHIVES = 'LOADING_ARCHIVES';
export const LOADING_ARCHIVES_SUCCESS = 'LOADING_ARCHIVES_SUCCESS';
export const LOADING_ARCHIVES_FAILURE = 'LOADING_ARCHIVES_FAILURE';