module.exports = {
  INITIAL_STATE: 'INITIAL_STATE',
  LOADING_STATE: 'LOADING_STATE',
  SUCCESS_STATE: 'SUCCESS_STATE',
  FAILURE_STATE: 'FAILURE_STATE',
  ALL_POSTS: 'ALL_POSTS',
  PART_POSTS: 'PART_POSTS',
};
